export const LOGIN_APP = "LOGIN_APP"
export const ADD_TASK_APP = "ADD_TASK_APP"
export const GET_TASK_APP = "GET_TASK_APP"
export const GET_TASK_LIST_APP = "GET_TASK_LIST_APP"
export const PUT_TASK_APP = "GET_TASK_LIST_APP"
export const IS_MENU_APP = "IS_MENU_APP"
